port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
ipv6: true
global-client-fingerprint: chrome
external-controller: '0.0.0.0:9090'
secret: 123456
external-ui: /root/clash/ui
dns:
  enable: true
  ipv6: true
  listen: 5353
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://doh.pub/dns-query
  fallback:
  - https://dns.alidns.com/dns-query
  - https://dns.twnic.tw/dns-query 
  - https://dns.google/dns-query
  fallback-filter:
    domain:
    - +.google.com
    - +.facebook.com
    - +.twitter.com
    - +.youtube.com
    - +.google.cn
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
